name: Send Vol2Vol Image Every 30 Min

on:
  schedule:
    # รันทุกนาทีที่ 0 และ 30 ของทุกชั่วโมง (เช่น 22:00, 22:30)
    - cron: '0,30 * * * *'
  workflow_dispatch: # ปุ่มกดรันเองสำหรับทดสอบ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests pytz

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_update.py
